spring:
  config:
    import:
      - application-secret.yml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 20
        format_sql: true
    show-sql: false

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  freemarker:
    template-loader-path: 'classpath:/mail-templates/'

  ai:
    openai:
      model: gpt-3.5-turbo
      api-key: "secretkey"

app:
  file-storage:
    local-root-folder: '/tmp/img'
    temp-folder: '/tmp/img/tmp'

  cors:
    add-mapping: '/**'
    allowed-origins: '*'
    allowed-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
      - 'OPTIONS'
    allowed-headers:
      - '*'
    max-age: 3600

#  cache:
#    default-cache:
#      max-entries-local-heap: 100
#      time-to-idle-seconds: 120
#      time-to-live-seconds: 200
#      eternal: false
#      disk-expiry-thread-interval-seconds: 1200
#      memory-store-eviction-policy: LRU
#    names:
#      - name: repos
#        max-entries-local-heap: 50
#        time-to-idle-seconds: 200
#        time-to-live-seconds: 300
#
logging:
  level:
    com.shk95.*: INFO
