spring:
  datasource:
    driver-class-name:
    url: <>
    username: <>
    password: <>
  redis:
    host: <>
    port: 0000
    password: 0000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 20
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <>
            client-secret: <>
            scope: <>

        provider:
          github:
            authorization-uri: <>
            token-uri: <>
            user-info-uri: <>
            user-name-attribute: <>

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  freemarker:
    template-loader-path: classpath:/mail-templates/

  mail:
    host: localhost
    port: 0
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
    username: asdf
    password: asdf

  config:
    import:
    - application-secret.yml
  profiles:
    include:
      - application-secret

app:
  front-page-url: 'http://localhost'

  mail-from: test@test.com

  token-secret-key: test

  file-storage:
    local-root-folder: /opt/data/files
    temp-folder: /opt/data/temp
    active: s3FileStorage
    s3-access-key: <Your S3 Access Key>
    s3-secret-key: <Your S3 Secret Key>
    s3-bucket-name: <Your S3 Bucket Name>
    s3-region: <Your S3 Region>

  image:
    command-search-path: /opt/homebrew/bin/ # nullable

  cdn:
    url: <S3 root URL>

  cors:
    add-mapping: '/**'
    allowed-origins: '*'
    allowed-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
      - 'OPTIONS'
    allowed-headers:
      - '*'
    max-age: 3600

logging:
  level:
    com.shk95.*: INFO
